# 1. Introduction to NumPy

## 1.1 What is NumPy?
NumPy (Numerical Python) is the foundational library for numerical computing in Python. It provides a powerful N-dimensional array object (`ndarray`), along with a large collection of mathematical functions to operate on arrays efficiently. Pandas is built on top of NumPy,every DataFrame column is a NumPy array under the hood.


## 1.2 Installation & Import

#### Install via conda
conda install numpy

In [106]:
import numpy as np

# 2. Core Data Structure: ndarray

## (A) 1D Arrays
A one dimensional array is a single line(or vector) of elements that have the same data type

(a vector is just a one dimensional array)



In [107]:
# Creating a one dimensional array
arr_1d = np.array([10,20,30,40,50])
arr_1d

array([10, 20, 30, 40, 50])

In [108]:
# Let's check the type of arr_1d
type(arr_1d)

numpy.ndarray

In [109]:
# Let's check the data type of arr_1d
arr_1d.dtype

dtype('int64')

In [110]:
# Let's see the shape of arr_1d
arr_1d.shape

(5,)

Here, even though the shape is (1,5), NumPy stores it without the row. That's why it just displays just (5,)

In [111]:
# Let's check the number of dimensions of arr_1d
arr_1d.ndim

1

In [112]:
# Let's check the size of arr_1d (tells you the number of elements inside)
arr_1d.size

5

In [113]:
# Creating a one dimensional array with a specified data type
arr_float = np.array([1, 2, 3], dtype=float)
arr_float.dtype

dtype('float64')

Here, every element is treated as a floating point number. This is used to make sure there is consistency while making the computations so we don't get type mismatches

## (B) 2D Arrays
A two dimensional array is like a grid. Instead of storing everything in one line, we store data in rows and columns

In [114]:
# Creating a two dimensional array
arr_2d = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100]
])
arr_2d

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [115]:
# Let's check the type of arr_2d
type(arr_2d)

numpy.ndarray

In [116]:
# Let's check the data type of arr_2d
arr_2d.dtype

dtype('int64')

In [117]:
# Let's see the shape of arr_2d
arr_2d.shape

(2, 5)

In [118]:
# Let's check the number of dimensions of arr_2d
arr_2d.ndim

2

In [119]:
# Let's check the size of arr_2d
arr_2d.size

10

## (C) 3D Arrays

A 3D array is basically a stack of 2D arrays (grids)

If:
- 1D array --> a line 
- 2D array --> a grid 
- 3D array --> multiple grids stacked together

In [120]:
# Creating a three dimensional array
arr_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [121]:
# Let's check the type of arr_3d
type(arr_3d)

numpy.ndarray

In [122]:
# Let's check the data type of arr_3d
arr_3d.dtype

dtype('int64')

In [123]:
# Let's see the shape of arr_3d
arr_3d.shape

(2, 2, 3)

Here, 
- There are 2 layers (ie. layer 0 and layer 1)
- There are 2 rows in each layer
- Each row has 3 columns

In [124]:
# Let's check the number of dimensions of arr_3d
arr_3d.ndim

3

In [125]:
# Let's check the size of arr_3d
arr_3d.size

12

# 3. Array Creation Functions
NumPy provides built-in functions to generate arrays without writing out values manually




## (A) np.zeros
This creates an array of all zeros



In [126]:
# Creating an 1D array using np.zeros
zeros_arr_1d=np.zeros(3)
zeros_arr_1d

array([0., 0., 0.])

In [127]:
# Creating an 2D array using np.zeros
zeros_arr_2d=np.zeros((2,3))
zeros_arr_2d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [128]:
# Creating an 3D array using np.zeros
zeros_arr_3d=np.zeros((2,3,3))
zeros_arr_3d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [129]:
# Let's check the data type of all the three zeros_arr
zeros_arr_1d.dtype , zeros_arr_2d.dtype , zeros_arr_3d.dtype

(dtype('float64'), dtype('float64'), dtype('float64'))

## (B) np.ones
This creates an array of all ones

In [130]:
# Creating an 1D array using np.ones
ones_arr_1d=np.ones(5)
ones_arr_1d

array([1., 1., 1., 1., 1.])

In [131]:
# Creating an 2D array using np.ones
ones_arr_2d=np.ones((3,6))
ones_arr_2d

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [132]:
# Creating an 3D array using np.ones
ones_arr_3d=np.ones((3,6,9))
ones_arr_3d

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [133]:
# Let's check the data type of all the three ones_arr
ones_arr_1d.dtype , ones_arr_2d.dtype , ones_arr_3d.dtype

(dtype('float64'), dtype('float64'), dtype('float64'))

## (C) np.arange
`np.arange()` creates a NumPy array containing evenly spaced values within a specified range

In [134]:
range_arr=np.arange(1,11,1) # start, stop, step
range_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
even_range_arr=np.arange(0,51,2)
even_range_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

## (D) np.random
`np.random` is NumPy's module for generating random numbers

Common Functions:
- np.random.rand()    --> Random floats in [0, 1)
- np.random.randint() -->	Random integers
- np.random.random()  -->	Random floats in [0, 1)
- np.random.seed()    -->	Set seed for reproducibility

In [136]:
# 1. np.random.rand(d0, d1, ..., dn)

#where d0, d1, ..., dn are the dimensions of the output array

# Generates random floats between 0 and 1
rand_arr = np.random.rand(2, 3) 
rand_arr

array([[0.60999666, 0.83319491, 0.17336465],
       [0.39106061, 0.18223609, 0.75536141]])

In [137]:
# 2. np.random.randint(low, high=None, size=None)

# low  = lowest integer (inclusive)
# high = highest integer (exclusive)
# size = shape of output array

# Generates random integers
randint_arr = np.random.randint(1, 10, size=(2, 3))
randint_arr

array([[6, 6, 4],
       [6, 2, 2]], dtype=int32)

In [138]:
# 3. np.random.random(size=None)

# size = shape of output array

# Similar to rand(), but takes the shape as a tuple
random_arr = np.random.random((2, 3))
random_arr

array([[0.39515024, 0.92665887, 0.727272  ],
       [0.32654077, 0.57044397, 0.52083426]])

In [139]:
# 4. np.random.seed(seed

#They are pseudo-random numbers (they look random, but they aren't)
#It allows you to generate random numbers that are reproduceable
#seed = integer used to make results reproducible

In [140]:
#lets see an example without seed
print(np.random.randint(1, 10))
print(np.random.randint(1, 10))

8
5


Different outputs every time because NumPy automatically chooses a seed (usually based on system entropy or time)

In [141]:
np.random.seed(42)
print(np.random.randint(1, 10))

7


 A seed is the initial value that determines the sequence of "random" numbers generated by NumPy.
 Run the program today, tomorrow, or on another computer using the same NumPy version, the sequence starts the same way

 Think of the random generator as a giant book containing a fixed sequence:
 
 Seed 42 → 7, 4, 8, 5, 7, 3, 7, 8, ...
 
 Seed 100 → 9, 9, 4, 8, 8, 1, 5, 2, ...

 Seed 123 → 3, 3, 7, 2, 4, 7, 2, 1, ...

 The seed chooses which page of the book you start reading from

# 4. Viewing Arrays and Matrices

## (A) np.unique
`np.unique()` finds all the unique values in an array and removes duplicates

In [166]:
# Let's create a test array
test_arr = np.random.randint(1, 11, size=(5, 3))
test_arr

array([[ 2,  8,  6],
       [ 2,  5,  1],
       [10,  6,  9],
       [ 1, 10,  3],
       [ 7,  4,  9]], dtype=int32)

In [167]:
# Finding out the unique elements from the test_arr
np.unique(test_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

Note: It won't list all the elements between 1 through 10, but will list the unique (non-repeating ones) from the ones displayed

## (B) Indexing & Slicing

### (1) 1D indexing
same as Python lists

In [168]:
# Let's see the 1D array we created earlier
arr_1d

array([10, 20, 30, 40, 50])

```text
Value:  10   20   30   40   50
Index:   0    1    2    3    4
```

In [180]:
# Let's see the shape of arr_1d
arr_1d.shape

(5,)

In [169]:
# This gives the first element of 1D array (array indexing starts from zero)
arr_1d[0]

np.int64(10)

In [170]:
# This gives the second element of 1D array
arr_1d[1]

np.int64(20)

In [171]:
#  This gives the last element of 1D array
arr_1d[-1]

np.int64(50)

In [172]:
#  Let's perform slicing operations on 1D array
arr_1d[1:4] # starting from position 1 upto but not including position 4

array([20, 30, 40])

### (2) 2D indexing
rows and columns

In [181]:
# Let's see the 1D array we created earlier
arr_2d

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

```text
          Col0  Col1  Col2  Col3  Col4
        -------------------------------
Row 0 |    10    20    30    40    50
Row 1 |    60    70    80    90   100
```

In [182]:
# Let's see the shape of arr_2d
arr_2d.shape

(2, 5)

In [183]:
# This give the 0th row
arr_2d[0]

array([10, 20, 30, 40, 50])

In [184]:
# This give a specific element in Row 1 and Column 4
arr_2d[1, 4]

np.int64(100)

In [185]:
# This gives all rows from Column 1
arr_2d[:, 1]

array([20, 70])

# 5. Manipulating & comparing arrays

## (A) Arithmatic
Arithmetic manipulation refers to performing mathematical operations on the elements of a NumPy array.
NumPy applies these operations element-wise, meaning the operation is performed on each element of the array individually