# 1. Introduction

## 1.1 What is NumPy?
NumPy (Numerical Python) is the foundational library for numerical computing in Python. It provides a powerful N-dimensional array object (`ndarray`), along with a large collection of mathematical functions to operate on arrays efficiently. Pandas is built on top of NumPy,every DataFrame column is a NumPy array under the hood.


## 1.2 Installation & Import

#### Install via conda
conda install numpy

In [6]:
import numpy as np

# 2. Core Data Structure: ndarray

## (A) 1D Arrays
A one dimensional array is a single line(or vector) of elements that have the same data type

(a vector is just a one dimensional array)



In [32]:
#Creating a one dimensional array
arr_1d = np.array([10,20,30,40,50])
arr_1d

array([10, 20, 30, 40, 50])

In [48]:
#Let's check the type of arr_1d
type(arr_1d)

numpy.ndarray

In [51]:
#Let's check the data type of arr_1d
arr_1d.dtype

dtype('int64')

In [49]:
#Let's see the shape of arr_1d
arr_1d.shape

(5,)

Here, even though the shape is (1,5), NumPy stores it without the row. That's why it just displays just (5,)

In [54]:
#Let's check the number of dimensions of arr_1d
arr_1d.ndim

1

In [56]:
#Let's check the size of arr_1d (tells you the number of elements inside)
arr_1d.size

5

In [34]:
#Creating a one dimensional array with a specified data type
arr_float = np.array([1, 2, 3], dtype=float)
arr_float.dtype

dtype('float64')

Here, every element is treated as a floating point number. This is used to make sure there is consistency while making the computations so we don't get type mismatches

## (B) 2D Arrays
A two dimensional array is like a grid. Instead of storing everything in one line, we store data in rows and columns

In [42]:
#Creating a two dimensional array
arr_2d = np.array([
    [10,20,30,40,50],
    [60,70,80,90,100]
])
arr_2d

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [50]:
#Let's check the type of arr_2d
type(arr_2d)

numpy.ndarray

In [53]:
#Let's check the data type of arr_2d
arr_2d.dtype

dtype('int64')

In [43]:
#Let's see the shape of arr_2d
arr_2d.shape

(2, 5)

In [47]:
#Let's check the number of dimensions of arr_2d
arr_2d.ndim

2

In [57]:
#Let's check the size of arr_2d
arr_2d.size

10

## (C) 3D Arrays

A 3D array is basically a stack of 2D arrays (grids)

If:
- 1D array --> a line 
- 2D array --> a grid 
- 3D array --> multiple grids stacked together

In [37]:
#Creating a three dimensional array
arr_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
#Let's check the type of arr_3d
type(arr_3d)

numpy.ndarray

In [59]:
#Let's check the data type of arr_3d
arr_3d.dtype

dtype('int64')

In [44]:
#Let's see the shape of arr_3d
arr_3d.shape

(2, 2, 3)

Here, 
- There are 2 layers (ie. layer 0 and layer 1)
- There are 2 rows in each layer
- Each row has 3 columns

In [60]:
#Let's check the number of dimensions of arr_3d
arr_3d.ndim

3

In [61]:
#Let's check the size of arr_3d
arr_3d.size

12